[
    {
        "id": 298028063,
        "name": "CVE-2014-0472",
        "full_name": "christasa\/CVE-2014-0472",
        "owner": {
            "login": "christasa",
            "id": 35037256,
            "avatar_url": "https:\/\/avatars0.githubusercontent.com\/u\/35037256?v=4",
            "html_url": "https:\/\/github.com\/christasa"
        },
        "html_url": "https:\/\/github.com\/christasa\/CVE-2014-0472",
        "description": "CVE-2014-0472 Django unexpected code execution using reverse()",
        "fork": false,
        "created_at": "2020-09-23T16:21:57Z",
        "updated_at": "2020-09-27T10:27:15Z",
        "pushed_at": "2020-09-27T10:27:13Z",
        "stargazers_count": 1,
        "watchers_count": 1,
        "forks_count": 0,
        "forks": 0,
        "watchers": 1,
        "score": 0
    }
]